name: FlaskApp

on:
  push:
    # * is a special character in YAML so you have to quote this string
#- cron:  "*/15 * * * *"



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi   
    
#  publish_docker_mage:
 #   needs: build
  #  runs-on: ubuntu-latest
   # steps:       
    #- uses: actions/checkout@v3  
    #- name: Build Docker image
     # run: |
      #  docker build . --file Dockerfile --tag emilyswitz/devops-repository
  #  - uses: actions/checkout@v3  
   # - name: Push into Docker Hub
    #  run: |
     #   docker push emilyswitz/devops-repository    
  
  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Tests
      run: |
        python -m pytest  
    
 
  publish_dockerImage:
    needs: test
    runs-on: ubuntu-latest
       
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}   
    - uses: actions/checkout@v3  
    - name: Build Docker image
      run: |
        docker build . --file Dockerfile --tag emilyswitz/devops-repository
    - uses: actions/checkout@v3  
    - name: Push into Docker Hub
      run: |
        docker push emilyswitz/devops-repository  
  Release docker container to Heroku:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Release docker container to Heroku
      uses: gonuit/heroku-docker-deploy@v1.3.3 # GitHub action name (leave it as it is).
      with:
        email: ${{ secrets.HEROKU_EMAIL }}
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        dockerfile_directory: ./
        dockerfile_name: Dockerfile
        docker_options: "--no-cache"
        process_type: web
